services:
  backend:
    container_name: backend
    build: .
    env_file: .prod.env
    command: bash -c "alembic upgrade head && uvicorn src.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:13-alpine
    env_file: .prod.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
