services:
  backend:
    container_name: backend
    build: .
    env_file: .prod.env
    command: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  # ds:
  #   container_name: ds
  #   build: ./DS
  #   env_file: .env
  #   command: bash -c "uvicorn src.main:app --reload --host 0.0.0.0 --port 8080"
  #   volumes:
  #     - ./DS:/app
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #     - backend

  db:
    container_name: db
    image: postgres:13-alpine
    env_file: .prod.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
