"""empty message

Revision ID: d5ebde9ec4b4
Revises: 5d649930b830
Create Date: 2023-12-05 20:16:04.401419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5ebde9ec4b4'
down_revision: Union[str, None] = '5d649930b830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productdealer', sa.Column('date', sa.Date(), nullable=False))
    op.create_foreign_key(None, 'productdealer', 'dealerprice', ['key', 'date', 'dealer_id'], ['product_key', 'date', 'dealer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productdealer', type_='foreignkey')
    op.drop_column('productdealer', 'date')
    # ### end Alembic commands ###
