"""empty message

Revision ID: c5aa66fbda5e
Revises: 8d28d2a91b95
Create Date: 2023-12-06 09:35:52.917062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5aa66fbda5e'
down_revision: Union[str, None] = '8d28d2a91b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'productdealer', ['key', 'dealer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productdealer', type_='unique')
    # ### end Alembic commands ###
