"""empty message

Revision ID: 8d28d2a91b95
Revises: d5ebde9ec4b4
Create Date: 2023-12-05 23:58:14.902019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d28d2a91b95'
down_revision: Union[str, None] = 'd5ebde9ec4b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('productdealer_key_date_dealer_id_fkey', 'productdealer', type_='foreignkey')
    op.drop_column('productdealer', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productdealer', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.create_foreign_key('productdealer_key_date_dealer_id_fkey', 'productdealer', 'dealerprice', ['key', 'date', 'dealer_id'], ['product_key', 'date', 'dealer_id'])
    # ### end Alembic commands ###
