"""empty message

Revision ID: 0284b06e239c
Revises: 568ac8d6eb01
Create Date: 2023-11-25 22:35:35.355114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0284b06e239c'
down_revision: Union[str, None] = '568ac8d6eb01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productdealer',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('dealer_id', 'product_id')
    )
    op.create_unique_constraint(None, 'dealerprice', ['product_key', 'date', 'dealer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dealerprice', type_='unique')
    op.drop_table('productdealer')
    # ### end Alembic commands ###
