"""empty message

Revision ID: 568ac8d6eb01
Revises: 4230ff22b68e
Create Date: 2023-11-25 21:19:49.288080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '568ac8d6eb01'
down_revision: Union[str, None] = '4230ff22b68e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productdealer')
    op.drop_constraint('dealerprice_product_key_key', 'dealerprice', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('dealerprice_product_key_key', 'dealerprice', ['product_key'])
    op.create_table('productdealer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dealer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], name='productdealer_dealer_id_fkey'),
    sa.ForeignKeyConstraint(['key'], ['dealerprice.product_key'], name='productdealer_key_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='productdealer_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='productdealer_pkey')
    )
    # ### end Alembic commands ###
