"""empty message

Revision ID: 91e8e8cdf4e1
Revises: 0284b06e239c
Create Date: 2023-11-26 00:18:29.326924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91e8e8cdf4e1'
down_revision: Union[str, None] = '0284b06e239c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productdealer', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productdealer', 'id')
    # ### end Alembic commands ###
